### PR TITLE
Save preferences

### PR DESCRIPTION
**Pull request by rolandomunoz**
This is an alternative way you can use to make the blocks `form/endform` to remember the values you inserted.
In this approach, the values are stored in a `preferences.txt`. When a script is called, a copy of it is done. Then, this new copy also includes the preference values stored in `preferences.txt`
By doing so, the core script is not modified. This way, it is more easy to keep track of the relevant changes using git.

I also added more extensions to `preferences/extensions.txt`

### CODE REVIEW

**Review by jeanphilippegoldman — COMMENTED** [review]
if path contains a dot, extension extractions crashes. can you fix ?

**Review by jeanphilippegoldman — COMMENTED** [review]
precising aif as extension still opens aiff.
it is a special trick for that extension ?
i mean if i put wa instead of wav , does it work ?

**Review by jeanphilippegoldman — COMMENTED** [review]
setting extension (in open files) to *
makes a crash. please fix

**Review by jeanphilippegoldman — COMMENTED** [review]
leaving blank the extension field acts differently for open_file (grabs all) and resample_file (grabs none).

**Comment by rolandomunoz** [comment]
Uhm... there is something strange here.

I will list your observations here:

1. if path contains a dot, extension extractions crashes. can you fix ?
> I have tried with this path `/home/rolando/Desktop/test/.temp` in my computer and it works well. Did you mean this?

2. precising aif as extension still opens aiff. it is a special trick for that extension ? i mean if i put wa instead of wav , does it work ?
> In mi version, if a put `aif` or `wa`, the plug-in does not open any file. This is so in `Open files...`, `Resample files...` and `Get durations...`
Also, the code should avoid this extensions in `Open files...` since `aif` is not in the extension list.
 
3. setting extension (in open files) to * makes a crash. please fix
> In my machine, it does not crash. The plug-in only does not open any file.

4. leaving blank the extension field acts differently for open_file (grabs all) and resample_file (grabs none).
> You're right. What should we do here? 1) when leaving blank the extension in `resample_file`, open all audio files? 2) Use a `*` to open all files and do not open anything when the field is empty?

As I said before,  there is something strange. I wonder how did you test the new changes? Did you make a copy of the project from my repository? In that case, did you download the files of the branch [save_preferences](https://github.com/rolandomunoz/plugin_filetools/tree/save_preferences)?
When I get home, I will test this plug-in in my other computer (Windows). I'll tell you later.

**Comment by jeanphilippegoldman** [comment]
1 if path contains a dot, extension extractions crashes:
i mean stuff like /home/user/corpus.new/sound.wav

2. aif aiff
ok maybe it's due to native Read files... on Windows. lets skip this issue then, as long as partial extensions do not open trigger unfortunate openings

3 i take this in charge and will make a commit after PR merging on this matter
4 i will throw an issue for that

**Pull request merged**
